spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/OrderBooks
spring.datasource.username=user
spring.datasource.password=password

spring.mvc.hiddenmethod.filter.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/changelog/changelog.xml
